"""The base revision. Manually tweaked. (user.password kwarg 'length' removed, user.json kwarg 'astext' removed)

Revision ID: 4701d5186146
Revises: 
Create Date: 2017-01-05 18:14:49.393103

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4701d5186146'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('menu_left', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('menu_right', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_name'), 'page', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sqlalchemy_utils.types.password.PasswordType(), nullable=False),
    sa.Column('registered_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('banned', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('bio', sa.Text(), server_default='', nullable=False),
    sa.Column('bio_html', sa.Text(), nullable=True),
    sa.Column('emojis', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('show_email', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('brewer', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('admin', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('json', postgresql.JSONB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_table('beer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('published', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('last_edit', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('listed', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beer_name'), 'beer', ['name'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('published', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('last_edit', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('beer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beer_id'], ['beer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_index(op.f('ix_beer_name'), table_name='beer')
    op.drop_table('beer')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_page_name'), table_name='page')
    op.drop_table('page')
    # ### end Alembic commands ###
