version: '2'
services:
    # PostgreSQL database image
    db:
        image: postgres
        restart: always
        volumes:
            - "db_volume:/var/lib/postgresql/data"
        environment:
            - POSTGRES_USER=thebeerarchive
            - POSTGRES_DB=thebeerarchive
        env_file:
            - ./passwords.env # Contains POSTGRES_PASSWORD
        ports:
            - "5432:5432" # todo: remove

    # Nginx static web & proxy server
    nginx:
        image: nginx
        restart: always
        links:
            - app
        volumes_from:
            - app
            - certbot
        volumes:
            - "./conf/nginx:/etc/nginx/conf.d:ro"
        ports:
            - "8000:80"
            - "8043:443"

    certbot:
        build: ./certbot
        volumes:
            - "./le:/etc/letsencrypt"
            #- "ssl_volume:/etc/letsencrypt"
            - "./log:/var/log"
        command: "certonly -n -t --email admin@dries007.net --agree-tos --webroot -w /etc/letsencrypt -d vps0.dries007.net"

    # The python app. Runs flask
    # todo: move to uwsgi
    app:
        build: ./app
        restart: always
        links:
            - db
        volumes:
            - "./app:/usr/src/app:ro"
        environment:
            - FLASK_APP=app.py
            - FLASK_DEBUG=1
        ports:
            - "5000:5000" # todo: remove
        command: "python -m flask run --host=0.0.0.0"

volumes:
    db_volume:
    ssl_volume:
