version: '2'
services:
    # PostgreSQL database image
    db:
        image: postgres
        restart: always
        volumes:
            - "db_volume:/var/lib/postgresql/data"
        env_file:
            - ./settings.env
            - ./passwords.env
        ports:
            - "5432:5432" # todo: remove

    # Nginx static web & proxy server
    nginx:
        image: nginx
        restart: always
        links:
            - app
        volumes_from:
            - app
            - certbot
        volumes:
            - "./conf/nginx:/etc/nginx/conf.d:ro"
        ports:
            - "8000:80"
            - "8043:443"

    certbot:
        build: ./certbot
        volumes:
            - "./run/le:/etc/letsencrypt"
            # - "ssl_volume:/etc/letsencrypt"
            - "./run/log:/var/log"
        command: "certonly -n -t --email admin@dries007.net --agree-tos --webroot -w /etc/letsencrypt -d bier.dries007.net -d beer.dries007.net"

    # The python app. Runs flask
    # todo: move to uwsgi
    app:
        build: ./app
        restart: always
        hostname: app
        links:
            - db
        volumes:
            - "./app:/usr/src/app"
        env_file:
            - ./settings.env
            - ./passwords.env
        ports:
            - "5000:5000" # todo: remove
        command: "python -m uBlog runserver --host=0.0.0.0"
#        command: "sleep 1000"

volumes:
    db_volume:
    ssl_volume:
