version: '2'
services:
    db:
        image: postgres
        restart: always
        volumes:
            - "./persist/db:/var/lib/postgresql/data"
        environment:
            - POSTGRES_USER=thebeerarchive
            - POSTGRES_DB=thebeerarchive
        env_file: 
            - ./passwords.env
        ports:
            - "5432:5432"

    nginx:
        image: nginx
        restart: always
        links:
            - app
        volumes_from:
            - app
        volumes:
            - "./conf/nginx:/etc/nginx/conf.d:ro"
            - "./persist/logs:/var/log/nginx"
        ports:
            - "80:80"
        
    app:
        build: ./app
        restart: always
        links:
            - db
        volumes:
            - "./app:/usr/src/app:ro"
        environment:
            - FLASK_APP=app.py
            - FLASK_DEBUG=1
        ports:
            - "5000:5000"
        command: "python -m flask run --host=0.0.0.0"
