version: '2'
services:
    # PostgreSQL database image
    db:
        image: postgres
        restart: always
        volumes:
            - "db_volume:/var/lib/postgresql/data"
        env_file:
            - ./settings.env
            - ./passwords.env
        ports:
            - "5432:5432" # Fixme: Remove if you don't want DB access from the outside world.

    # Nginx static web & proxy server
    nginx:
        image: nginx
        restart: always
        links:
            - app
        volumes_from:
            - app
            - certbot
        volumes:
            - "./conf/nginx:/etc/nginx/conf.d:ro"
        ports:
            - "80:80"     # Fixme: These ports may need to be changed.
            - "443:443"   # Fixme: These ports may need to be changed.
        labels:
          - "certbot_nginx_hup" # Fixme: Must be unique, globally. Gets used by certbot to reload the config.

    # LetsEncrypt
    certbot:
        build: ./certbot
        restart: always
        volumes:
            - "./run/le:/etc/letsencrypt"
            - "./run/log:/var/log"
            - "/var/run/docker.sock:/var/run/docker.sock:ro" # Fixme: Make sure this is the right location
            - "/usr/bin/docker:/usr/bin/docker:ro"           # Fixme: Make sure this is the right location
        env_file:
            - ./settings.env
        command: "/root/certbot_script.sh"

    # The python app. Runs flask
    # todo: move to uwsgi in deployment
    app:
        build: ./app
        restart: always
        hostname: app
        links:
            - db
        volumes:
            - "./app:/usr/src/app"
        env_file:
            - ./settings.env
            - ./passwords.env
        ports:
            - "5000:5000"
        command: "python -m uBlog runserver --host=0.0.0.0"

volumes:
    db_volume:
